apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-uost
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-uost
    app.kubernetes.io/part-of: tkrw-pr714-0075-0018-app
  name: devfile-sample-uost
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-uost
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-uost
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0018-tenant/tkrw-pr714-0075-0018-app/devfile-sample-uost@sha256:0529205f6457ebb55d7705087a3d7d0efdf0dea68bdfc575de319bbf5d92edda
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
